# Welcome to Jekyll!
#
# This config file is meant for settings that affect the entire site, values
# which are expected to be set up once and rarely need to be edited after that.
# For technical reasons, `jekyll serve` does not automatically reload this file
# after it is changed. In that case, the server process has to be restarted.


oneflow-skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Epopeia Space"
title_separator          : "•"
subtitle                 : " " # displayed in the masthead below the title, using " " for no subtitle
url                      : "https://epopeia.space" # the base hostname & protocol for the site
baseurl                  : "epopeia.space" # the subpath of the site, e.g. "/blog"
repository               : "miguelsan/oneflow_theme-the_project" # GitHub username/repo-name
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/EPOPEIA.webp" # Site logo displayed in the masthead
#logo                     : "/assets/images/Epopeia_logo_placeholder.webp" # Site logo displayed in the masthead
show-popup               : true # set to false if not needed / to show a cookie-banner / cdn-usage popup
                                # edit the popup itself in the respective /includes file
masthead_title           : " "  # overrides the website title displayed in the masthead, use " " for no title
sticky-masthead          : true # if true, masthead/navigation bar will stay visible when the user scrolls down
                                # if false, it will move out of sight when scrolling
#masthead-opacity         : 0.85 # set to any value between 0 and 1
                                # only relevant if masthead is sticky
background-image         : # '/assets/images/header.webp' # remove / out-comment, if background image not needed
background-image-mobile  : # '/assets/images/header.webp' # for a different (e.g upright) background image for mobile
background-image-overlay : rgba(255, 255, 255, 0.5) # Set overlay for the background image



# Site Footer.
footer:
  links: # for every link to have in the footer
    - label: "Website"
      icon: "fa fa-globe"
      url: "https://epopeia.space"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto: contact at epopeia dot space"
    # - label: "LinkedIn"
    #   icon: "fab fa-linkedin"
    #   # url:
    # - label: "X/Twitter"
    #   icon: "fab fa-x-twitter"
    #   # url:
    # - label: "Facebook"
    #   icon: "fab fa-facebook"
    #   # url:
    # - label: "GitHub"
    #   icon: "fab fa-github"
    #   url: "https://github.com/miguelsan"
    # - label: "Instagram"
    #   icon: "fab fa-instagram"
    #   url: "https://www.instagram.com/epopeia_space/"
    # - label: "YouTube"
    #   icon: "fab fa-youtube"
    #   url: "https://www.youtube.com/channel/CODE"
  copyright: "Epopeia Sources"
  # creator: # Remove this if unwanted "created by" in the footer
  #     name: "Miguel San Miguel"
  #     url: "https://miguelsanmiguel.com"



# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

